[template]
src = "sql/apache.sql.tpl"
dest = "/tmp/apache.sql"
mode = "0600"
keys = [
  "/drupal/db",
  "/drupal/db/user",
  "/drupal/db/pass"
]
reload_cmd="mysql -h ${DB_ENDPOINT} -u${MYSQL_ROOT_USER} -p${MYSQL_ROOT_PASSWORD} < /tmp/apache.sql"
